name: flux_firebase
description: A Firebase package for FluxStore apps
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fstore:
    path: ../../
  inspireui: 2.2.7

  # FIREBASE PACKAGES
  firebase_core: 3.9.0
  firebase_analytics: 11.3.6
  firebase_auth: 5.3.4
  firebase_remote_config: 5.2.0
  firebase_dynamic_links: 6.0.11
  cloud_firestore: 5.6.0

  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_core_platform_interface: ^5.4.0
  firebase_analytics_platform_interface: ^4.2.8
  firebase_auth_platform_interface: ^7.4.10
  firebase_remote_config_platform_interface: ^1.4.47
  firebase_dynamic_links_platform_interface: ^0.2.6+47
  cloud_firestore_platform_interface: ^6.6.0
  firebase_messaging_platform_interface: 4.5.49

  # PUSH NOTIFICATION
  firebase_messaging: 15.1.6

  # OTHERS
  intl: ^0.19.0
  timeago: 3.7.0
  flutter_local_notifications: ^19.0.0
  share: 2.0.4
  provider: 6.1.2
  collection: any
  easy_debounce: 2.0.3
  app_links: ^3.4.3

flutter:
  uses-material-design: true

